#!/usr/bin/env bash
# backup and compress my databases
mysqldump -u root -p --all-databases --single-transaction --routines --events > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
tar -czvf "$file_name" backup.sql
